[package]
name = "cx"
version = "0.1.5"
edition = "2021"
rust-version = "1.85"
repository = "https://github.com/1unarzDev/cx"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
crossterm = "0.28"
ratatui = "0.29"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
sha2 = "0.10"
libc = "0.2"
signal-hook = "0.3"
tar = "0.4"
flate2 = "1"

[dev-dependencies]
tempfile = "3"
